(function(a){function f(c,e){var f=b;b=document.location.hash;a(window).trigger("jQuery.hashchange",{before:f,after:b})}function g(){if(b!=document.location.hash){var c=b;b=document.location.hash;a(window).trigger("jQuery.hashchange",{before:c,after:b})}}a.fn.hashchange=function(b){a(window).bind("jQuery.hashchange",b);return this};a.observeHashChange=function(d){d=a.extend({},a.observeHashChange.defaults,d);"undefined"!==typeof window.onhashchange?(b=document.location.hash,window.onhashchange=f):
(null==b&&(b=document.location.hash),null!=c&&clearInterval(c),e!=d.interval&&(c=setInterval(g,d.interval),e=d.interval))};var b=null,c=null,e=0;a.observeHashChange.defaults={interval:100};a.observeHashChange()})(jQuery);function strspn(a,f,g,b){var c,e=0,d=0;g=g?0>g?a.length+g:g:0;b=b?0>b?a.length+b-g:b:a.length-g;a=a.substr(g,b);for(d=0;d<a.length;d++){g=0;b=a.substring(d,d+1);for(e=0;e<=f.length;e++)if(c=f.substring(e,e+1),b==c){g=1;break}if(1!=g)break}return d}
function isCanvasSupported(){var a=document.createElement("canvas");return!(!a.getContext||!a.getContext("2d"))}
var STPreloader=function(a){function f(){a.width=a.height=32;e.translate(16,16);e.rotate(u+=0.12);++m;e.rotate(m*Math.PI/6);for(var b=0;12>b;b++)e.globalAlpha=b/12,e.save(),e.fillStyle="rgba(0, 0, 0, 0.2)",g(e,4,-2,12,6,4),e.restore(),e.save(),e.fillStyle="rgba(0, 0, 0, 0.2)",g(e,5,-1,10,4,4),e.restore(),e.save(),e.fillStyle="#fff",e.fillRect(6,0,8,2),e.restore(),e.transform(q,t,-t,q,0,0);e.restore()}function g(a,b,c,d,e,f){a.beginPath();a.moveTo(b,c+f);a.lineTo(b,c+e-f);a.quadraticCurveTo(b,c+e,
b+f,c+e);a.lineTo(b+d-f,c+e);a.quadraticCurveTo(b+d,c+e,b+d,c+e-f);a.lineTo(b+d,c+f);a.quadraticCurveTo(b+d,c,b+d-f,c);a.lineTo(b+f,c);a.quadraticCurveTo(b,c,b,c+f);a.fill()}var b=isCanvasSupported(),c=!1;if(a){if(b)var e=a.getContext("2d"),d=null,t=Math.sin(Math.PI/6),q=Math.cos(Math.PI/6),m=0,u=0;else{var r=a;a=null;e="canvas"!=$(a).prop("tagName")?a:this.createAlternativeCvs(r)}this.createAlternativeCvs=function(b){a=$('<span class="alternativeRotator" />');$(b).before(a);return a};this.start=
function(){if(!c)if(c=!0,b)$(a).show(),d=setInterval(f,66);else{var e=$('<img src="/images/loading.gif" width="100%" height="100%" />');$(a).html(e)}};this.stop=function(){b?null!=d&&(clearInterval(d),d=null):$(a).html("");$(a).hide();c=!1};this.destroy=function(){this.stop();$(a).remove()}}};
(function(a){var f,g,b={relatedDomains:"klobic.com klobic.com".split(" "),apiUrl:"//stapi.klobic.net/",klobicUrl:"//www.klobic.com/",filesUrl:"//files.klobic.net/",lang:"en",ajaxUrl:"index.php",localAjaxUrl:"/stapi.php",ajaxDataType:"jsonp",ajaxType:"get",containerId:"userApiCont",loginPage:"/login.html",sessionExpiredPage:"/session-inactive.html",
loginTerminal:null,openCloseTime:300,loadPage:function(){var c=location.href.split("#")[1]||null;if(c&&1<c.length){var e={},c=c.split("&"),d,f;for(d in c)if(0==d){e.page=b.urldecode(c[d]);if("st-"!=e.page.substr(0,3))return;e.page=e.page.substr(3)}else f=c[d].split("="),e[b.urldecode(f[0])]=b.urldecode(f[1]);a("#"+b.containerId).userApi(e)}},isCreateAccountPage:function(){return"create-account.html"==location.pathname.split("/").pop()},isLoginPage:function(){var a=location.pathname.split("/").pop();
return"flipsnack"===b.terminal&&"function"===typeof isFlipsnackLoginPage?isFlipsnackLoginPage():"login.html"==a||location.pathname===this.loginPage},urlencode:function(a){return encodeURIComponent(a).replace(/!/g,"%21").replace(/'/g,"%27").replace(/\(/g,"%28").replace(/\)/g,"%29").replace(/\*/g,"%2A").replace(/%20/g,"+")},urldecode:function(a){return decodeURIComponent((a+"").replace(/\+/g,"%20"))},goToLogin:function(a,e){var d=("flipsnack"==b.terminal&&"undefined"!=typeof langPre?langPre:"")+b.loginPage,
f="";if(a){if("undefined"!=typeof e&&e)for(var q in e)f+="&"+q+"="+e[q];d+="?next="+this.urlencode(a)+f+"&terminal="+this.urlencode(b.terminal)}location.href=d},showFacebookPopin:function(){var a=b.apiUrl+"fblogin/index.php?"+b._getPopinExtraParams();window.open(a,"_blank","left="+(screen.width-981)/2+",top="+(screen.height-512)/2+",width=981,height=512,toolbar=0,resizable=1,menubar=0,status=1,scrollbars=no",!0);return!1},showTwitterPopin:function(){var a=b.apiUrl+"twitter/index.php?"+b._getPopinExtraParams();
window.open(a,"_blank","left="+(screen.width-800)/2+",top="+(screen.height-754)/2+",width=800,height=754,toolbar=0,resizable=1,menubar=0,status=1,scrollbars=no",!0);return!1},showGooglePopin:function(){var a=b.apiUrl+"google/?"+b._getPopinExtraParams();window.open(a,"_blank","left="+(screen.width-450)/2+",top="+(screen.height-510)/2+",width=450,height=510,toolbar=0,resizable=1,menubar=0,status=1,scrollbars=no",!0);return!1},showOpenIDPopin:function(a){var e=b.apiUrl+"OpenID/index.php?"+b._getPopinExtraParams(),
d=(screen.width-q)/2,f=(screen.height-g)/2,q,g,e=e+("&type="+b.urlencode(a));switch(a){default:q=450;g=364;break;case "yahoo":q=492,g=585}window.open(e,"_blank","left="+d+",top="+f+",width="+q+",height="+g+",toolbar=0,resizable=1,menubar=0,status=1,scrollbars=no",!0);return!1},_getPopinExtraParams:function(){var a=b.loginTerminal||b.terminal,e;e="terminal="+b.urlencode(b.terminal);e+="&loginTerminal="+b.urlencode(a);"undefiend"!=typeof b.referralHash&&(e+="&campaignHash="+b.urlencode(b.referralHash));
b.cookie("UAuref")&&(e+="&uref="+b.urlencode(b.cookie("UAuref")));b.lang&&(e+="&lang="+b.lang);return e},checkLogin:function(c){b.closeFacebookPopup();b.sessionId=c;c={page:"check-login",PHPSESSID:c,lang:b.lang};a("#UALErememberme").attr("checked")&&(c.rememberme=1);"function"==typeof UA_setExtraOptions&&UA_setExtraOptions(c);"undefined"==typeof f?a("<div />").userApi(c):f.userApi(c)},getUserOccupationSelector:function(a){b.ajax({data:{page:"user-occupation-selector",lang:b.lang},complete:function(){},
success:function(b){200!=b.code&&regError(b.data);a(b.data)}})},closeFacebookPopup:function(){a(window).focus()},showAccountInactiveMessage:function(){b.getText("account_deactivated_message",function(a){alert(a)})},onUploadProfilePhoto:function(a,b){STonProfilePhoto(a,b)},colapse:function(){b.close(f);b.colapsed=!0;var c=a(window).scrollTop();location.href="#";0<c&&a(window).scrollTop(c);return!1},jump:function(a){window.location.href=a},open:function(c,e){b.isOpen||(0<a(window).scrollTop()&&a("html,body").animate({scrollTop:0},
b.openCloseTime/2),c.slideDown(b.openCloseTime,function(){b.isOpen=!0;!0!=e&&f.userApi(g)}),c.show())},close:function(c){if("undefined"==typeof c&&(c=f,!c))return;c.slideUp(b.openCloseTime);b.isOpen=!1;c=a("#UA-header");c.find(".uhcc").show();c.find(".uhco").hide()},headerInited:!1,isSnackWS:function(){return"snackwebsites"==b.terminal},initHeader:function(c){var e=a("#"+b.containerId),d=a("#UAH-myacclinks"),g=a("#UA-header .UA-myaccount h4"),q=a("#UA-header .UA-myaccount .UAH-uinfo"),m=a("#UA-header"),
u=a("#UA-container");e.hide().addClass("userApi "+b.terminal).html(b.userApiContainerHtml);e.find("a.UAclose").click(b.colapse);if("klobic"!==b.terminal){this.headerInited?m.find("#UA-allsnacksbox").remove():(e=a("<div />").attr("id","UA-allsnacksbox-overlay"),a("body").append(e,a("#UA-allsnacksbox")));m.find("#search-field").focus(function(){a(this).parent().addClass("focus")}).blur(function(){a(this).parent().removeClass("focus")});m.find(".UA-logo i").click(function(){var c=a("#UA-header .UA-logo"),
d=51,e=51;b.isLogged()?e=d=69:b.isSnackWS()&&(d=25,e=50);"klobic"==b.terminal?a("#UA-allsnacksboxcontent").css({left:c.offset().left-5+"px",top:d+"px"}):a("#UA-allsnacksboxcontent").css({left:c.offset().left-5+"px",top:e+"px"});a(".UA-d-arrow.headerMenu").hide();a(".UA-x").show();a("#UA-allsnacksboxcontent").fadeIn("fast");a("#UA-allsnacksbox-overlay").show()});a("#UA-allsnacksbox .inf i, #UA-allsnacksbox-overlay").click(function(){a("#UA-allsnacksbox").fadeOut("fast");a("#UA-allsnacksboxcontent").fadeOut("fast");
a("#UA-allsnacksbox-overlay").hide();a(".UA-x").hide();a(".UA-d-arrow.headerMenu").show()});c.find("a").click(function(){a(this).attr("href")==location.hash&&0<a(window).scrollTop()&&(a.browser.safari?a("body"):a("html")).animate({scrollTop:0},300)});var r=!1;d.hover(function(){a(this).stop(!0,!0).fadeIn("fast");setTimeout(function(){r=!0},200)},function(){a(this).fadeOut("fast");r=!1;q.css("visibility","visible")}).click(function(){r&&(a(this).fadeOut("fast"),r=!1)});"flipsnack"===b.terminal?(g.mouseenter(function(){var b=
a(window).width()-(a(this).offset().left+a(this).width())-3,c;q.css("visibility","hidden");"block"===d.css("display")?d.stop(!0,!0).show():(c=0===u.length?g.offset().top- -42:g.offset().top- -42-u.offset().top,d.css({right:b+"px",top:c+"px"}),d.stop(!0,!0).fadeIn("fast"))}),g.mouseleave(function(b){a(b.target).hasClass("profile")||a(b.target).hasClass("hello-text")?(b.preventDefault(),b.stopImmediatePropagation()):(d.fadeOut("fast"),q.css("visibility","visible"))}),d.on("mouseenter",function(a){a.preventDefault();
a.stopImmediatePropagation()})):c.find(".UA-myaccount h4").hover(function(){var d="klobic"==b.terminal,e=a("#UAH-myacclinks"),f;f=12;var q=a(window).width()-(a(this).offset().left+a(this).width())-35;d&&(f=15);0===u.length?f=g.offset().top-f:(d=u.offset().top,f=g.offset().top-f-d);"fixed"===c.css("position")&&(f=-15);e.css({right:q+"px",top:f+"px"});e.stop(!0,!0).fadeIn("fast")});a("#UAH-myacclinks a").click(function(){a("#UAH-myacclinks").fadeOut("fast")})}setTimeout(function(){a("a").each(b.rewriteLink)},
500);!a("#UAisLogged").val()&&(b.cookie("UAemail")&&!b.remembermeCalled)&&(b.remembermeCalled=!0,m={page:"auto-login",user:b.cookie("UAemail"),pass:b.cookie("UApass")},"undefined"==typeof f?a("<div />").userApi(m):f.userApi(m));this.headerInited=!0},rewriteLink:function(){if(this.host&&!a(this).data("skip-rewrite")){var c=this.host.split(":")[0];if(c!=window.location.host){var e=!1,d;for(d in b.relatedDomains)if(-1!=c.indexOf(b.relatedDomains[d])){e=!0;break}if(e){c=a(this).attr("href").split("?");
e=[];if(c[1]){var f=c[1].split("&"),g;for(g in f){var m=f[g].split("=");e[m[0]]="undefined"!=typeof m[1]?decodeURIComponent(m[1]):null}}b.cookie("UAuref")?e.uref=b.cookie("UAuref"):e.uref=null;e.UA_PHPSESSID="undefined"!=typeof b.sessionId&&""!=b.sessionId?b.sessionId:null;"undefiend"!=typeof b.referralHash&&(null!=b.referralHash&&b.referralHash)&&(e.ref=b.referralHash,b.referralDate&&(e.refDate=b.referralDate));g="";for(d in e)e[d]&&(g=""!=g?g+"&":g+"?",g+=d+"="+b.urlencode(e[d]));a(this).attr("href",
c[0]+g)}}}},onSessionExpired:function(){b.cookie("UAemail")&&(b.cookie("UAemail",null,{path:"/"}),b.cookie("UApass",null,{path:"/"}));"undefined"!==typeof mixpanel&&("undefined"!==typeof mixpanel.config&&"undefined"!==typeof mixpanel.config.token)&&b.cookie("mp_"+mixpanel.config.token+"_mixpanel",null,{path:"/"});location.href=b.sessionExpiredPage},getTheVip:function(){location.href="#st-buy-points";return!1},getTheVipExtended:function(){this.getTheVip();return!1},freeuserConvert:function(){b.ajax({data:{page:"free_to_premium"}})},
addService:function(a,e,d){d="";if("undefined"!=typeof e&&e)for(var f in e)d+="&"+f+"="+e[f];location.href="#st-buy-points"+d+"&service="+b.urlencode(a);return!1},onBuyPointsTimeout:null,onBuyPoints:function(){clearInterval(b.onBuyPointsTimeout);b.onBuyPointsTimeout=setInterval(b.reloadPoints,5E3)},buyPoints:function(){location.hash="podsnack"==b.terminal?"#st-buy-points":"#st-buy-points&plan=points";return!1},buyPointsContainer:null,onBuyPointsCreate:null,_buyPointsBS:function(a){if(!b.isLogged())return b.goToLogin(location.pathname+
location.hash),!1;bsBuyPoints(a)},_buyPoints:function(c){var e="undefined"!==typeof c.extraParams?c.extraParams:void 0;if("filesnack"==b.terminal)return"function"==typeof openDiscontinuedPopin&&openDiscontinuedPopin(),!1;if(!b.isLogged())return b.goToLogin(location.pathname+location.hash,e),!1;c=c||{};var d=b.buyPointsContainer;if(null==d){d=a("<div />").attr({id:"UA_dialog_buypoints"});if("klobic"==b.terminal&&!jQuery.ui){var f=setInterval(function(){jQuery.ui&&(clearInterval(f),b._buyPoints(c))},
50);a.getScript("//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js");return!1}d.dialog({modal:!0,autoOpen:!1,resizable:!1,width:"flipsnack"==b.terminal?756:682,minHeight:480,close:function(){var b=a(window).scrollTop();location.href="#";b&&a(window).scrollTop(b)}});d.parent().attr({id:"UA_dialog"}).addClass("UAdialog");b.buyPointsContainer=d;"function"===typeof this.onBuyPointsCreate&&this.onBuyPointsCreate.call(this)}var g=!!d.data("dialog");g&&d.dialog("option","title","");g&&!d.dialog("isOpen")&&
d.dialog("open");d.html(b._dialogGetLoader());var e="service coupon methodBuy views vipOnly type pug upgrade hm flipsnack_api_uploads".split(" "),m={page:"buy-points"},u,r;for(u=0;r=e[u];u++)c[r]&&(m[r]=c[r]);c.methodBuy||(c.methodBuy=2,"flipsnack"==b.terminal&&(c.methodBuy=8));m.ssl="https:"===location.protocol?1:0;var R=function(e){d.html("<div>"+e+"<div>");e=a('<a href="#">Try again</a>');e.click(function(){b._buyPoints(c)});d.append("<br>",e)},M=function(a,b){var c=0;"trial"===b.type?c=a.price:
"upgrade"===b.type?b.upgradeDiscountValue?(c=parseFloat(b.upgradeDiscountValue),c+=Math.max(0,(a.price-c)*parseFloat(b.value)/100)):c=a.price*parseFloat(b.value)/100:c="procentual"===b.type?a.price*parseFloat(b.value)/100:parseFloat(b.value);return c};b.ajax({data:m,error:function(a){R("Internal server error")},success:function(e){if(200!==e.code)300==e.code?b.goToLogin():R(e.data);else{d.html(e.data.content);g&&(d.dialog("option","title",e.data.popinTitle),d.dialog("option","closeText",e.data.popinCloseText+
" X"),d.dialog("option","dialogClass",b.terminal+"_go_premium_popin"));e.data.upgradeCoupon&&(c.coupon=e.data.upgradeCoupon);var f=e.data.selectedServiceHash,t=e.data.isSelectedServiceInList,m=e.data.selectedService||null,r=e.data.haveActiveRecurringProfile||!1,y=d.find("form.paymentForm"),W=e.data.alreadyReceivedCampaignsBonus,s=null,N="",p={},w=d.find("div.couponCont"),D=d.find(".serviceInfo"),S=w.find("div.discountInfo"),O=w.find("div.couponDescription"),C=d.find(".plans div.plan"),U=function(a){var b=
w.find("div.msg");if(a){var c=0;if(s.flags&8)c=parseFloat(s.campaigns_budget);else if(s.flags&4&&(c=parseFloat(p.price-M(p,s)),!c||0>c))c=0;!(0>=p.price-M(p,s))&&!W&&("snack-vip-yearly"===p.hash&&100>c?c=100:"vip-extended-yearly"===p.hash&&200>c&&(c=200));a=a.replace("{amount}",parseFloat(c.toFixed(2)));"upgrade"==s.type&&(a=a.replace("%s",M(p,s).toFixed(2)));b.removeClass("cerr").addClass("cnot").html(a);b.fadeIn("fast")}else b.html("").hide()},P=function(a,f){var k=a.price;if(f||p.hash!=a.hash||
p.price!=a.price){p=a;y.find('input[name="serv"]').val(p.hash);y.find('input[name="views"]').val(p.views||0);y.find('input[name="flipsnack_api_uploads"]').val(p.flipsnack_api_uploads||0);t||(D.find(".details").text(p.name),D.find(".price").text("$"+p.price.toFixed(2)),D.find(".desc").html(p.description),C.hide(),d.find(".plans-container").hide(),g&&e.data.popinTitleUpgrade&&d.dialog("option","title",e.data.popinTitleUpgrade),D.show());if(s){k=M(p,s);S.find(".discount").text("$"+k.toFixed(2));var h=
a.price-k;0>h&&(h=0);k=h;S.find(".total").text("$"+h.toFixed(2));S.show();var v=d.find(".paywith"),l=d.find(".paymethods"),m=d.find(".fulldiscountinfo"),A=d.find(".freeTrialInfo"),ea=d.find(".sbut");"trial"==s.type?(v.hide(),ea.hide(),A.show().find("input[name=method_buy]").attr("checked",!0),A.find(".trialDays").html(s.trial_days),A.find("#trialSubmit").val(A.find("#trialButtonText").text())):(0===h?(l.hide(),m.show().find("input[name=method_buy]").attr("checked",!0)):(l.show().find("input[name=method_buy][value="+
c.methodBuy+"]").attr("checked",!0),m.hide()),A.hide());if(0<h&&p.recursive){var v=0,v="procentual"===s.subscription_type?p.price*parseFloat(s.subscription_value)/100:parseFloat(s.subscription_value),fa=a.price-v,K="";b.getMultipleTexts(JSON.stringify(["initial_payment","recurrent","recurrent_monthly","recurrent_yearly"]),function(a){var b=JSON.parse(a);a=b.initial_payment;var c=b.recurrent,d=b.recurrent_monthly,b=b.recurrent_yearly;a=a.replace("%s",h.toFixed(2).toString());c=c.replace("%s",fa.toFixed(2).toString());
b=b.replace("%s",p.months.toString());b=b.replace("%s",p.months.toString());K=a+" "+c;switch(p.months){case 1:K+=" "+d;break;default:K+=" "+b}O.html(K).show()})}else O.hide();U(N);v=w.find("input[name=coupon]");s.number!=v.val()&&v.val(s.number)}v=y.find(".noteValidLicence");r&&p.recursive&&(!s||"trial"!=s.type)?v.show():v.hide();v=y.find(".note-campaigns-bonus");"snack-vip-yearly"!==p.hash&&"vip-extended-yearly"!==p.hash?v.hide():v.show();if(k>__maxPayflowProAmount){k=d.find(".paymethod.method6,.paymethod.method8");
v=k.find("input[name=method_buy]");if(6==c.methodBuy||8==c.methodBuy)l=d.find(".paymethod.method2 input[name=method_buy]"),l.attr("checked",!0),l.triggerHandler("click"),c.methodBuy=2;v.attr("disabled",!0);k.addClass("disabled")}else k=d.find(".paymethod.method6,.paymethod.method8"),v=k.find("input[name=method_buy]"),k.removeClass("disabled"),v.attr("disabled",!1)}};if("flipsnack"!=b.terminal&&(d.find(".plans").addClass("col"+C.length),g)){var l=682;3<d.find(".plans .plan").length&&"klobic"==
b.terminal&&(l=890);d.dialog("option","width",l);d.dialog("option","position","center")}C.length?(d.find(".plans-categories").length&&(d.find("#forYearlyPlans").click(function(){"object"==typeof UA_trackEvent&&UA_trackEvent.ga("Popin actions","annual prices");d.find("#forMonthlyPlans").removeClass("sel");a(this).addClass("sel");d.find(".plans.monthly").hide();d.find(".plans.yearly").show();var b=d.find(".plans.monthly .plan.selected").attr("rel");if("undefined"!=typeof b)for(u=b;5>=u;u++)if(d.find(".plans.yearly .plan.p"+
u).length){d.find(".plans.yearly .plan.p"+u).click();break}}),d.find("#forMonthlyPlans").click(function(){"object"==typeof UA_trackEvent&&UA_trackEvent.ga("Popin actions","monthly prices");d.find("#forYearlyPlans").removeClass("sel");a(this).addClass("sel");d.find(".plans.yearly").hide();d.find(".plans.monthly").show();var b=d.find(".plans.yearly .plan.selected").attr("rel");if("undefined"!=typeof b)for(u=b;5>=u;u++)if(d.find(".plans.monthly .plan.p"+u).length){d.find(".plans.monthly .plan.p"+u).click();
break}})),C.each(function(){var d=this,e=a(this);if(!e.hasClass("free")){var k=e.find('select[name="add_serv"]'),h=e.find('select[name="views"]'),t=e.find('select[name="flipsnack_api_uploads"]'),l=!!k.data("recursive");e.click(function(a){C.removeClass("selected");e.addClass("selected");e.find('input[name="selservice"]').attr("checked",!0);a=k.find("option:selected");a={months:parseInt(a.data("months"))||0,recursive:l,price:parseFloat(a.data("price")),hash:a.val(),views:parseInt(h.val())||0,flipsnack_api_uploads:parseInt(t.val())||
0};P(a);"snack-vip-yearly"===a.hash||"vip-extended-yearly"===a.hash?e.find(".inf .bonus-campaigns").show():e.find(".inf .bonus-campaigns").hide()});var m=!!e.data("showPricePerPoint");k.change(function(b,c){var f=k.find("option:selected"),g=f.data("months"),h=f.data("price"),t=a(d).find("div.price");(f=g?h/g:m?h/f.data("points"):h)&&f!==parseInt(f)||l&&99<f?(f!==parseInt(f)&&(f=f.toFixed(2)),t.addClass("small")):t.removeClass("small");t.find("strong").text(f);c||e.triggerHandler("click")});h.change(function(){var d=
{views:a(this).val(),service:p.hash,coupon:s?s.number:"",methodBuy:c.methodBuy,vipOnly:c.vipOnly||0,pug:c.pug||0,pug:c.hm||0,upgrade:c.upgrade||0,userClick:!1};t.length&&(d.flipsnack_api_uploads=t.val());c.type&&(d.type=c.type);g||(d.content=c.content);b._buyPoints(d)});t.length&&t.change(function(){var d={flipsnack_api_uploads:a(this).val(),service:p.hash,coupon:s?s.number:"",methodBuy:c.methodBuy,vipOnly:c.vipOnly||0,pug:c.pug||0,pug:c.hm||0,upgrade:c.upgrade||0,userClick:!1};h.length&&(d.views=
h.val());c.type&&(d.type=c.type);g||(d.content=c.content);b._buyPoints(d)});k.find('option[value="'+f+'"]').length&&(k.val(f),e.triggerHandler("click"));k.triggerHandler("change",!0)}})):m&&m.hash?P(m,!0):D.html("Invalid product").show();l=d.find(".pointsHref");l.click(function(){var b=a(this).parent().find(".plan");b.is(":visible")?b.slideUp("fast"):b.slideDown("fast");var b=a(this),c=a(this).html();b.html(b.data("alttext")).data("alttext",c);return!1});"flipsnack"==b.terminal&&(m||d.find(".plan.selected:visible").click(),
d.find(".plan.points").hasClass("selected")&&l.click());var H=d.find(".couponHref");H.click(function(){w.is(":visible")?w.slideUp("fast"):(w.slideDown("fast"),"object"==typeof UA_trackEvent&&UA_trackEvent.ga("Popin actions","discount"));var b=a(this),c=a(this).html();b.html(b.data("alttext")).data("alttext",c);return!1});var G=w.find("input[name=coupon]"),E=w.find("a.applycoupon");G.keypress(function(a){if(13==a.keyCode)return E.triggerHandler("click"),!1});E.click(function(){var a=w.find("div.msg"),
c=G.val();a.hide();O.hide();var d=function(b){a.removeClass("cnot").addClass("cerr").html(b);a.fadeIn("fast")};if(!c)return b.getText("complete_your_coupon",function(a){d(a)}),!1;var c={page:"check-coupon",coupon:c},e=b.getLoader(16);E.after(e).hide();b.ajax({data:c,complete:function(){e.remove();E.show()},success:function(a){if(200===a.code){var b=a.data;s=b.coupon;y.find("input[name=coupon]").val(s.number);a.data.service?(t=!1,P(a.data.service,!0)):P(p,!0);N=b.message;U(N);H.hide()}else d(a.data)}});
return!1});d.find(".paymethods input[name=method_buy]").each(function(){var b=a(this);b.click(function(){c.methodBuy=a(this).val();2==c.methodBuy?"object"==typeof UA_trackEvent&&UA_trackEvent.ga("Popin actions","paypal"):8==c.methodBuy&&"object"==typeof UA_trackEvent&&UA_trackEvent.ga("Popin actions","credit card");y.attr("target",6==c.methodBuy||8==c.methodBuy?"_self":"_blank")});b.val()==c.methodBuy&&(b.prop("checked",!0),b.triggerHandler("click"))});b.referralHash&&y.find("input[name=referralHash]").val(b.referralHash);
c.coupon&&(H.triggerHandler("click"),G.val(c.coupon),E.triggerHandler("click"));y.submit(function(){"object"==typeof UA_trackEvent&&UA_trackEvent.ga("Buy","place order");b.onBuyPoints();g?d.dialog("close"):(d.hide(),d.parent().append(b._dialogGetLoader()))});g||y.attr("target","_self");!1!==c.userClick&&"undefined"!=typeof dataLayerForGoogleTagManager&&(dataLayerForGoogleTagManager.push({event:"open_gopremium_popin"}),"undefined"!=typeof dataLayerForGoogleTagManager2&&dataLayerForGoogleTagManager2.push({event:"open_gopremium_popin"}));
d.find("div.c-mini-tooltip-ico,sup.bp-tooltip").each(function(){a(this).STtooltip({content:a(this).attr("title"),width:340});a(this).attr("title","")})}}});return!1},getText:function(c,e,d){if("function"==typeof e){d=d||{};var f=!0;a.isArray(c)||(c=[c],f=!1);for(var g={page:"get-text"},m=0;m<c.length;m++)g["index["+m+"]"]=c[m];d.raw&&(g.raw=!0);b.ajax({data:g,success:function(a){200==a.code&&(f||(a.data=a.data[c[0]]),e(a.data))}})}},getTexts:function(a,b,d){return this.getText(a,b,d)},getMultipleTexts:function(a,
e){"function"==typeof e&&b.ajax({data:{page:"get-multiple-texts",indexes:a},success:function(a){200==a.code&&e(a.data)}})},_dialogGetLoader:function(){var c=b.apiUrl+"images/ajax-loader-white-big.gif?v2";return a("<img />").attr({src:c}).css({margin:"0 auto",padding:"159px 0",display:"block"})},getLoader:function(c){return a("<img />").attr({src:b.apiUrl+"images/ajax-loader.gif",width:c||32}).addClass("UAloader")},loadCss:function(b){a("link").attr({type:"text/css",href:b,rel:"stylesheet"}).appendTo("head")},
reloadPoints:function(){b.ajax({data:{page:"reload_points"},success:function(c){if(200==c.code){var e=a("#UAH-ptocheck").val();a("#UAH-points-container").html(c.data.display);var d=a("#UA-header").find(".UAHpointsinfo");c.data.premium?d.unbind("click").attr("href","#st-order-history").removeClass("goPremiumHeaderImage").html("").text(c.data.sevicePlan):0<c.data.total_points&&(d.attr("href","#st-order-history"),d.find("span").text(c.data.total_points));d=parseInt(c.data.premium||0)+"-"+parseInt(c.data.total_points||
0);e!=d&&("function"==typeof UA_onChangePoints&&UA_onChangePoints(c.data.premium,c.data.total_points),clearInterval(b.onBuyPointsTimeout))}}})},replaceApiHeader:function(c){if("flipsnack"!==b.terminal){var e=a("#UA-header");e.html(c);b.initHeader(e)}},analyticsDomainCheck:function(c){a.each(b.relatedDomains,function(a,d){document.domain!=d&&(document.domain.substring(4)!=d&&"jmphandled"!=c.attr("rev")&&"undefined"!=typeof c.attr("href")&&(0==c.attr("href").indexOf("http://www."+d)||0==c.attr("href").indexOf("https://www."+
d)||0==c.attr("href").indexOf("http://"+d)||0==c.attr("href").indexOf("https://"+d)))&&c.click(function(){b.analyticsGoToRelatedDomain(this.href,this.target);return!1})})},getUrlVars:function(){for(var a=[],b,d=window.location.href.slice(window.location.href.indexOf("?")+1),d=d.split("#"),d=d[0],d=d.split("&"),f=0;f<d.length;f++)b=d[f].split("="),a.push(b[0]),a[b[0]]=b[1];return a},cookie:function(a,b,d){if("undefined"!=typeof b){d=d||{};null===b&&(b="",d.expires=-1);var f="";if(d.expires&&("number"==
typeof d.expires||d.expires.toUTCString))"number"==typeof d.expires?(f=new Date,f.setTime(f.getTime()+864E5*d.expires)):f=d.expires,f="; expires="+f.toUTCString();var g=d.path?"; path="+d.path:"",m=d.domain?"; domain="+d.domain:"";d=d.secure?"; secure":"";document.cookie=[encodeURIComponent(a),"=",encodeURIComponent(b),f,g,m,d].join("")}else{b=null;if(document.cookie&&""!=document.cookie){d=document.cookie.split(";");for(f=0;f<d.length;f++)if(g=jQuery.trim(d[f]),g.substring(0,a.length+1)==a+"="){b=
decodeURIComponent(g.substring(a.length+1));break}}return b}},analyticsGoToRelatedDomain:function(c,e){a("#ST-AnalyticsForm").remove();a("<form/>").hide().appendTo("body").attr("id","ST-AnalyticsForm");var d=a("#ST-AnalyticsForm");d.attr("action",c).attr("method","POST");e&&d.attr("target",e);var f="__utma __utmb __utmc __utmz __utmv __utmx".split(" "),g;for(g=0;g<f.length;g++)b.cookie(f[g])&&a("<input>").attr("name",f[g]).val(b.cookie(f[g])).appendTo(d);"undefined"!=typeof stTrackingSystem&&a("<input>").attr("name",
"stTrackingSystem").val(stTrackingSystem).appendTo(d);"undefined"!=typeof stTrackingObjectSystem&&a("<input>").attr("name","stTrackingObjectSystem").val(stTrackingObjectSystem).appendTo(d);d.submit()},konami:function(a){a.keyCode==b.konamiparams.code[b.konamiparams.step]?b.konamiparams.step++:b.konamiparams.step=0;b.konamiparams.step==b.konamiparams.code.length&&(b.konamiparams.step=0,b.ajax({data:{page:"konami"},success:function(a){!0==a.data.redirect?location.href=a.data.href:alert(a.data)}}))},
checkSessionStatus:function(){if(b.sessionId){var a={page:"check-session"};"function"==typeof UA_setExtraOptions&&UA_setExtraOptions(a);b.ajax({data:a,success:function(a){a.data.expired&&(b.onSessionExpired(),b.replaceApiHeader(a.data.header),b.colapse());a.data.logged||(b.sessionId="")}})}},isLogged:function(){return!!b.sessionId},preloadImage:function(a){(new Image).src=b.apiUrl+"images/"+a},gtmSetOrderFirstSession:function(){b.ajax({data:{page:"gtm-set-order-first-session"}})},ajax:function(c){var e=
{url:b.localAjaxUrl,type:b.ajaxType,dataType:b.ajaxDataType};c.data||(c.data={});c.data=a.extend({terminal:b.terminal,PHPSESSID:b.sessionId||"",langPre:b.langPre||"",lang:b.lang||"en"},c.data);return a.ajax(a.extend(e,c))},disableRegisterLoginForm:function(){a(".right-side .help-width").append(a('<div class="UA-loader-hover" />'));a("input,button").attr("disabled",!0)},enableRegisterLoginForm:function(){a("input,button").attr("disabled",!1);a(".right-side .UA-loader-hover").remove()},userApiContainerHtml:"",
konamiparams:{code:[38,38,40,40,37,39,37,39,66,65],step:0},isOpen:!1,colapsed:!1,referralHash:null,referralDate:null,inited:!1,konamiInited:!1,logged:!1,autoLogging:!1,remembermeCalled:!1,checkSessionStatusTimeout:60};a.fn.userApi=function(c){function e(){var a=null,c=null,d=!1;k.mousedown(function(b){2==b.button&&(d=!0,c=b.pageY,a=b.pageX)});k.mouseup(function(e){if(!0==d&&(d=!1,!(e.pageY>c)&&!(50<Math.abs(a-e.pageX))&&!(21>c-e.pageY)))return b.colapse(),!1})}function d(){var a="#st-buy-points";
h.coupon&&(a+="&coupon="+h.coupon);h.service&&(a+="&service="+h.service);location.href=a}function t(){b.autoLogging=!0;var a={user:h.user,pass:h.pass};"function"==typeof UA_setExtraOptions&&UA_setExtraOptions(a);l({data:a,complete:function(a){b.autoLogging=!1;"function"==typeof UA_onAutoLoginEnd&&UA_onAutoLoginEnd(a)},success:function(a){!0==a.data.logged?(q(a.data),"undefined"!=typeof dataLayerForGoogleTagManager&&(dataLayerForGoogleTagManager.push({event:"login"}),"undefined"!=typeof dataLayerForGoogleTagManager2&&
dataLayerForGoogleTagManager2.push({event:"login"}))):(b.replaceApiHeader(a.data.header),p())}})}function q(a,c){b.sessionId=a.PHPSESSID;a.header&&b.replaceApiHeader(a.header);a.rememberme&&(b.cookie("UAemail",a.email,{expires:365,path:"/"}),b.cookie("UApass",a.pass,{expires:365,path:"/"}));if(h.coupon||h.service)d();else if(h.next)if("st-"==h.next.substr(0,3))location.href="#"+h.next;else{var e=h.next,e=0<=e.search(/\?/)?e+"&":e+"?",e=e+("UA_PHPSESSID="+a.PHPSESSID);location.href=e;return}"function"===
typeof UA_onLogin&&UA_onLogin(a.PHPSESSID)}function m(){l({success:function(a){200==a.code?F(a.data):H(a.data)}})}function u(){var a={page:"check-login",isOpen:b.isOpen};h.rememberme&&(a.rememberme=1);"function"==typeof UA_setExtraOptions&&UA_setExtraOptions(a);l({data:a,success:function(a){!0==a.data.logged&&q(a.data,!0)}})}function r(){var b={page:"order-history"};"undefined"!==typeof h.agencyManager&&(b.agencyManager=h.agencyManager);l({data:b,success:function(b){F(b.data);k.find("td.order_id input").each(function(){var b=
a(this),c=b.parent();b.click(function(){b.select();b.addClass("selected")});b.blur(function(){c.find("input").hide();c.find("div").fadeIn("fast");b.removeClass("selected")});c.hover(function(){c.find("div").hide();c.find("input").stop(!0,!0).fadeIn("fast")},function(){c.find("input").hasClass("selected")||(c.find("input").hide(),c.find("div").stop(!0,!0).fadeIn("fast"))})});k.find("p.cancelRecurringProfile a").click(function(){w("cancel_your_profile",function(a){confirm(a)&&R()});return!1})}})}function R(){var a=
{page:"cancel-recurring-profile"};"function"==typeof UA_setExtraOptions&&UA_setExtraOptions(a);l({data:a,success:function(a){200==a.code&&("function"==typeof UA_onCancelProfile&&UA_onCancelProfile(),k.find("p.cancelRecurringProfile").remove(),b.reloadPoints())}})}function M(){l({data:{page:"change-email-html"},success:function(a){F(a.data);Y()}})}function Y(){var a=k.find("form.UAchangeEmailForm");a.submit(function(){var b=a.find("input[name='email']"),c=a.find("input[name='password']"),d=a.find(".uanotice"),
e=a.find(".uaerr"),f=a.find("input"),b=b.val(),c=c.val();d.hide();e.hide();f.attr("disabled",!0);l({data:{page:"change-email",email:b,password:c},complete:function(){d.is(":visible")||f.attr("disabled",!1)},success:function(a){200==a.code?d.html(a.data).show():e.html(a.data).show()}});return!1})}function Z(){l({data:{page:"change-password-html"},success:function(a){F(a.data);aa()}})}function aa(){var b,c,d;function e(a){var c=T.find(".err1");c.hide();var d=h.find("input[name='password1']").val();
if(!0!=a&&""==d)return b=!1;l({data:{page:"check-old-password",password:d},success:function(d){!1==d.data.valid?(b=!1,c.html(d.data.message).fadeIn("fast")):(b=!0,!0==a&&h.submit())}})}function f(a){var b=T.find(".err2");b.hide();var d=h.find("input[name='password2']").val();if(!0!=a&&""==d)return c=!1;4>d.length?(c=!1,w("password_to_short",function(a){b=T.find(".err2");b.html(a).fadeIn("fast")})):(c=!0,!0==a&&h.submit())}function g(a){var b=T.find(".err3"),c=h.find("input[name='password3']").val(),
e=h.find("input[name='password2']").val();b.hide();if(!0!=a&&""==c)return d=!1;c!=e?(d=!1,w("passwords_not_match",function(a){b=T.find(".err3");b.html(a).fadeIn("fast")})):(d=!0,!0==a&&h.submit())}var h=k.find("form.UAchangePasswordForm");h.find("a.updatePasswordButton").click(function(){h.submit();return!1});var T=k.find("div.cpErrorMessage");h.find("input[name='password1']").blur(e);h.find("input[name='password2']").blur(f);h.find("input[name='password3']").blur(g);d=c=b=!1;h.submit(function(){h.find(".uanotice").hide();
if(!1==b)return e(!0),!1;if(!1==c)return f(!0),!1;if(!1==d)return g(!0),!1;var k=h,T=k.find("#password1"),m=k.find("#password2"),p=k.find("#password3"),t=k.find("a.updatePasswordButton"),q=G(t,"black");k.find("input").each(function(){a(this).attr("disabled",!0)});l({data:{page:"update_password",current_password:T.val(),new_password1:m.val(),new_password2:p.val()},complete:function(){k.find("input").each(function(){a(this).attr("disabled",!1)});q.remove();t.show()},success:function(e){200==e.code?
(k.find(".uanotice").html(e.data).fadeIn("fast"),"function"==typeof UA_onPasswordChange&&UA_onPasswordChange()):H(e.data);k.find("input[type='password']").each(function(){a(this).val("")});d=c=b=!1}});return!1})}function ba(){l({data:{page:"account-options"},success:function(a){F(a.data);ca();"function"===typeof UA_onAccountOptionsLoad&&UA_onAccountOptionsLoad(k)}})}function ca(){var c=k.find("form.UAaccountOptionsForm");c.find("i.uni").STtooltip({content:c.find("div.toolTipContent"),width:420});
c.find("i.unna").STtooltip({content:c.find("div.notAcceptedTooltip"),width:420});k.find("form.UAaccountOptionsForm a.deleteAccount").click(function(){w("delete_account_notice",function(a){confirm(a)&&s()});return!1});var d=null;c.find("input[name=username]").keyup(function(){var b=a(this).val();clearTimeout(d);var e=c.find("span.usernameStatus");b?d=setTimeout(function(){l({data:{page:"check-unique-username",username:b},success:function(a){"na"==a.data?w("notAcceptedUsername",function(a){e.find("span").html(a)}):
e.find("span").html(a.data);e.show();"200"==a.code?a.data&&(e.find("i").show(),c.find("i.unna").hide(),e.find("span").removeClass("err").addClass("ok")):(e.find("i").hide(),e.find("span").removeClass("ok").addClass("err"),"na"==a.data&&c.find("i.unna").css("display","inline-block"))}})},1E3):(e.find("i").hide(),e.find("span").text("").removeClass("ok").addClass("err"))});c.find("div.profilePhotoC .remove").click(function(){c.find("div.profilePhotoC .remove").css("visibility","hidden");c.find("div.profilePhotoC img").error();
l({data:{page:"remove-profile-photo"},success:function(a){"200"!=a.code&&(c.find("div.profilePhotoC img").load(),c.find("div.profilePhotoC .remove").css("visibility","visible"));try{window.UPRefresh()}catch(b){console.log(b)}}})});y();var e=c.find(".socialInputs"),f=c.find("span.inputTarget"),g=c.find(".socialIcon a");g.click(function(){var b=a(this);g.removeClass("selected");b.addClass("selected");f.find("label.info span").text(b.data("tooltip"));var c=e.find("input[name="+b.data("name")+"]");c.length&&
(b=f.find("input"),f.prepend(c),e.append(b),setTimeout(function(){c.focus();try{var a=c.val().length;c[0].setSelectionRange(a,a)}catch(b){a=c.val(),c.val(""),c.val(a)}},50));return!1});c.find("input.si").keyup(function(){var b=a(this).val().replace(/\s/g,"");b&&"http://"!=b?c.find(".socialIcon a."+a(this).attr("name")).addClass("enabled"):c.find(".socialIcon a."+a(this).attr("name")).removeClass("enabled")});var h=new UAClipboard.Client;h.setHandCursor(!0);h.setText(k.find("#UAacchash").val());h.glue("UAaccopy");
h.addEventListener("mouseDown",function(b){var c=a(b.domElement).parent().find("i");setTimeout(function(){var d=a(b.domElement);c.show();d.hide()},150);setTimeout(function(){var d=a(b.domElement);c.hide();d.show()},5E3)});k.find("#UAaccopy").click(function(){return!1});c.submit(function(){var e=a(this),f=e.find("#screenname"),g=e.find(".uaerr"),h=e.find(".uanotice"),m=e.serialize();g.hide();h.hide();clearTimeout(d);c.find("span.usernameStatus").hide();e.find("input").each(function(){a(this).attr("disabled",
!0)});var K=e.find("a.updateAccountButton"),p=G(K,"black");"function"===typeof UA_onAccountOptionsBeforeUpdate&&UA_onAccountOptionsBeforeUpdate(k);l({data:{page:"update_account_information",data:m},complete:function(){e.find("input:not(.dontEnable)").each(function(){a(this).attr("disabled",!1)});e.find("input[name='email']").attr("disabled",!0);p.remove();K.show();f.focus()},success:function(d){200==d.code?(h.html(d.data.message).fadeIn("fast"),a("#UAH-myacclinks h4 strong").text(d.data.name),a("#UA-header .UA-myaccount h4 strong").text(d.data.name),
d.data.username&&d.data.username.length&&c.find("input[name=username]").prop("disabled",!0).addClass("dontEnable"),"function"==typeof UA_onUpdateAccountInfoSuccess&&UA_onUpdateAccountInfoSuccess(b.sessionId),setTimeout(function(){b.colapse();try{window.UPRefresh()}catch(a){}},500)):g.html(d.data).fadeIn("fast")}});return!1})}function y(){var c=k.find("form.UAaccountOptionsForm");c.find("div.profilePhotoC img").load(function(){a(this).show();a(this).css({"margin-left":(-this.width>>1)+"px","margin-top":(-this.height>>
1)+"px"});c.find("div.profilePhotoC .placeholder").hide();c.find("div.profilePhotoC .remove").css("visibility","visible")}).error(function(){a(this).hide();c.find("div.profilePhotoC .placeholder").show();c.find("div.profilePhotoC .remove").css("visibility","hidden")}).attr("src",b.filesUrl+"accounts/"+k.find("#UAacchash").val()+"/profile?_="+parseInt(1E4*Math.random()));W(c.find("input[name=profilePhoto]"),c)}function W(c,d){var e="uploadTempTarget"+A,f=k.find("form.UAaccountOptionsForm"),g=a(f).find(".profilePhotoC img");
0<a(".userApiContainer form#uploadFileTempForm"+A).length&&a(".userApiContainer form#uploadFileTempForm"+A).unbind().remove();var h=a("<form>").attr({method:"POST",enctype:"multipart/form-data",action:b.apiUrl+"?page=upload-profile-photo&terminal="+b.urlencode(b.terminal)+"&PHPSESSID="+b.sessionId,target:e,id:"uploadFileTempForm"+A}).bind("submit",function(b){g.remove();a("<img/>").css("display","none").insertBefore(f.find(".profilePhotoC .remove"));a(f).find("div.browse").append('<input type="file" name="profilePhoto" accept="image/png,image/jpeg"/>');
setTimeout(function(){y()},800)}).data({index:A,el:c}).css({position:"absolute",display:"block",left:"-9999px"}).html('<iframe id="'+e+'" name="'+e+'" src="" style="width:0;height:0;border:0px solid #fff;"></iframe>'),e={index:A},l;for(l in e)h.append('<input type="hidden" name="'+l+'" value="'+e[l]+'" />');c.bind("change",function(){if(a(this).val()){var b=(a(this).val()||"").split("."),b=b[b.length-1];-1!=a.inArray(b.toLowerCase(),["jpg","jpeg","png"])?(g.hide(),h.append(this).submit()):STonProfilePhoto(A,
-1)}});d.after(h)}function s(){var a={page:"delete-account"};"function"==typeof UA_setExtraOptions&&UA_setExtraOptions(a);l({data:a,success:function(a){200==a.code&&N(a)}})}function N(a){b.close(k);b.colapsed=!1;p();"function"==typeof UA_onLogout&&UA_onLogout();b.sessionId="";a&&a.data.header&&b.replaceApiHeader(a.data.header);"photosnack"!=b.terminal&&(location.href="#")}function p(){b.cookie("UAemail",null,{path:"/"});b.cookie("UApass",null,{path:"/"})}function w(a,c){b.getText(a,c)}function D(a){"flipsnack"===
b.terminal?(C(),X(k)):(a=a||"login-signup","create-account"==a&&(a="login-signup"),a={page:a},"function"==typeof UA_setExtraOptions&&UA_setExtraOptions(a),l({data:a,success:function(a){a.data.forceReload?location.reload():!0==a.data.logged?q(a.data,!0):200==a.code?F(a.data):H(a.data);"function"==typeof h.callback&&h.callback(a.code,a.data)}}))}function S(){l({data:{page:"login-signup",inline:"true"},success:function(c){!0==c.data.logged?q(c.data,!0):200==c.code?(a("#inlineLogin").html(c.data.content),
a("#inlineLogin").hide().fadeIn("fast"),(!c.logged||"flipsnack"==b.terminal)&&C()):H(c.data)}})}function O(){p();if(-1===a.inArray(b.terminal,"klobic flipsnack klobic snackwebsites podsnack photosnack".split(" ")))location.href=b.klobicUrl+"en/logout.html?terminal="+b.urlencode(b.terminal)+"&UA_PHPSESSID="+b.sessionId;else{var c={page:"logout"};b.isBlog&&(c.isBlog=1);"function"==typeof UA_setExtraOptions&&UA_setExtraOptions(c);l({data:c,success:function(a){N(a)}})}}function C(c){function d(){if(!b.preventLogin){var c=
G.val().replace(/^[\s\n\t\r]+|[\s\n\t\r]+$/g,"");G.val(c);f();c={page:"login",user:G.val(),pass:S.val(),captcha:L.find("input[name='captcha']").val(),captchaId:L.find("input[name='captchaId']").val(),loginTerminal:b.loginTerminal||""};n.find("input[name=rememberMe]").attr("checked")&&(c.rememberme=1);"function"==typeof UA_setExtraOptions&&UA_setExtraOptions(c);var h;"klobic"===b.terminal?h=new LoaderHover(n):(h=new UALoaderHover(n),"flipsnack"==b.terminal?k.find(".right-side .help-width").append(a('<div class="UA-loader-hover" />')):
k.find(".right-side").append(a('<div class="UA-loader-hover" />')),k.find("input,button").attr("disabled",!0));b.preventLogin=!0;l({data:c,complete:function(){k.find("input,button").attr("disabled",!1);G.focus()},error:function(){h.remove();k.find(".right-side .UA-loader-hover").remove()},success:function(c){if(200==c.code)!0==c.data.logged?q(c.data,!0):(b.preventLogin=!1,h.remove(),F(c.data.data));else if(b.preventLogin=!1,h.remove(),k.find(".right-side .UA-loader-hover").remove(),5==c.code)k.find("div.captcha-login").show(),
e(c.data.error);else if(4==c.code)g("login",c.data.id,c.data.src),e(c.data.error);else{if(3==c.code){e(c.data);n.find(".uaerr a").click(function(){d(a(this).attr("title"));return!1});var d=function(c){var d=new UALoaderHover(n);"flipsnack"==b.terminal?k.find(".right-side .help-width").append(a('<div class="UA-loader-hover" />')):k.find(".right-side").append(a('<div class="UA-loader-hover" />'));l({data:{page:"resend-activation-mail",email:c},complete:function(){d.remove();k.find(".right-side .UA-loader-hover").remove()},
success:function(a){200==a.code?n.html(a.data.content):H(a.data)}})}}else e(c.data);n.find("a.recovery").click(function(){E();I.find("#UAfpemail").focus().val(a(this).data("email")||"").blur();return!1})}}})}}function e(a){n.find(".uaerr").parent(":visible").children(".uaerr").html(a).fadeIn("fast")}function f(){n.find(".uaerr").html("").stop(!0).hide()}function g(a,b,c){a=n.find("div.captcha-"+a);a.find("img").attr("src",c);a.find("input[name='captcha']").val("");a.find("input[name='captchaId']").val(b);
a.show()}function m(){D(function(){f();var a=new UALoaderHover(n);k.find("input,button").attr("disabled",!0);var c={page:"username-create",loginTerminal:b.loginTerminal||"",username:B.val()};B.removeClass("err");l({data:c,complete:function(){k.find("input,button").attr("disabled",!1);a.remove()},success:function(a){200==a.code?("function"==typeof unsetRegisterCookie&&unsetRegisterCookie(),"object"==typeof UA_trackEvent&&(UA_trackEvent.intercom("set username"),UA_trackEvent.ga("Login","set up account")),
"flipsnack"==b.terminal?UA_onUsernameSubmit():(F(a.data),history.pushState(null,null,"/login.html?s=thankyou"),s())):(B.addClass("err"),r(a.data))}})})}function p(){b.ajax({data:{page:"username-create",loginTerminal:b.loginTerminal||""},success:function(a){200==a.code&&("function"==typeof unsetRegisterCookie&&unsetRegisterCookie(),"object"==typeof UA_trackEvent&&(UA_trackEvent.mixpanel("set up account",{"account type":"email"}),UA_trackEvent.ga("Login","set up account")),"flipsnack"==b.terminal?UA_onUsernameSubmit():
(F(a.data),history.pushState(null,null,"/login.html?s=thankyou"),s()))}})}function t(){if(!h.validS.email)return y(!0),!1;if(!h.validS.psw1)return C(!0),!1;f();var a={page:"signup-flipsnack",email:z.val(),screenname:Q.val(),password:J.val(),captcha:grecaptcha.getResponse(),newsletter:x.find("input[name=newsletter]").attr("checked")?1:0,loginTerminal:b.loginTerminal||""};B.length&&(a.username=B.val());P(b.referralHash)&&(a.campaignHash=b.referralHash);"function"==typeof UA_setExtraOptions&&UA_setExtraOptions(a);
var c=new UALoaderHover(n);b.disableRegisterLoginForm();l({data:a,complete:function(a,d){UAjustRegistered||(c.remove(),b.enableRegisterLoginForm())},success:function(a){200==a.code?("function"==typeof UA_onRegister&&UA_onRegister(a.data.user),q(a.data,!0)):4==a.code?r(a.data.error):r(a.data)}});return!1}function s(){"function"===typeof initThankYouPage&&initThankYouPage();k.find(".button-continue").click(function(){u()})}function u(a){"object"==typeof UA_trackEvent&&(UA_trackEvent.mixpanel("continue"),
UA_trackEvent.ga("Login","continue"));"function"==typeof UA_onRegisterContinue&&UA_onRegisterContinue(a)}function v(){if(!h.validS.email)return y(!0),!1;if(!h.validS.psw1)return C(!0),!1;if(!h.validS.screenname)return A(!0),!1;f();var c={page:"signup",email:z.val(),screenname:Q.val(),password:J.val(),captcha:x.find("input[name='captcha']").val(),captchaId:x.find("input[name='captchaId']").val(),newsletter:x.find("input[name=newsletter]").attr("checked")?1:0,banneradv:x.find("input[name=banneradv]").attr("checked")?
1:0,loginTerminal:b.loginTerminal||""};B.length&&(c.username=B.val());P(b.referralHash)&&(c.campaignHash=b.referralHash);"function"==typeof UA_setExtraOptions&&UA_setExtraOptions(c);var d=new UALoaderHover(n);k.find("input,button").attr("disabled",!0);l({data:c,complete:function(){k.find("input,button").attr("disabled",!1);d.remove()},success:function(b){200==b.code?(F(b.data),"function"==typeof UA_onRegister&&UA_onRegister(b.data.user),q(b.data,!0),k.find(".button-continue").click(function(){u()})):
4==b.code?(g("register",b.data.id,b.data.src),r(b.data.error),n.find('input[name="captcha"]:visible').addClass("err").bind("focus.remerr",function(){a(this).removeClass("err").unbind("focus.remerr")})):r(b.data)}});return!1}function r(a,b){b?w(a,function(a){e(a)}):e(a)}function y(a){z.removeClass("err");var b=z.val().replace(/^[\s\n\t\r]+|[\s\n\t\r]+$/g,"");z.val(b);if(!0!==a&&!z.val())return h.validS.email=!1;if(!U(z.val())||!z.val())return z.addClass("err"),z.val()?r("invalid_email_address",!0):
r("empty_email",!0),h.validS.email=!1,!0===a&&z.focus(),!1;setTimeout(function(){l({data:{page:"email_exists",email:z.val()},success:function(b){!0==b.data.exists?(0<z.filter(":visible").length&&(z.addClass("err"),e(b.data.message)),h.validS.email=!1,!0===a&&z.focus(),n.find(".uaerr").find("a").click(function(a){E();a.preventDefault()})):(f(),h.validS.email=!0,!0===a&&x.submit())}})},50);return!0}function A(a){h.validS.screenname=!1;Q.removeClass("err");if(!0!==a&&!Q.val())return!1;var b;b=Q.val();
b=/^[0-9A-Za-z_\- ]+$/.test(b)?!0:!1;if(b)f(),h.validS.screenname=!0,!0===a&&x.submit();else return Q.addClass("err"),Q.val()?r("name_invalid_caracters",!0):r("fill_in_your_name",!0),!1}function D(a){B.removeClass("err");B.val()?B.val()&&l({data:{page:"check-unique-username",username:B.val(),requireLogged:0},success:function(b){200!=b.code?(B.addClass("err"),r(b.data)):(f(),"function"==typeof a&&a())}}):"flipsnack"!==b.terminal?(B.addClass("err"),r("Username must be at least 5 characters long.")):
l({data:{page:"username-create",username:B.val()},success:function(a){200!=a.code&&(B.addClass("err"),r(a.data))}})}function C(a){h.validS.psw1=!1;J.removeClass("err");if(!0!==a&&""==J.val())return!1;if(4>J.val().length)return J.addClass("err"),""==J.val()?r("empty_password",!0):r("password_to_short",!0),!0===a&&J.focus(),!1;h.validS.psw1=!0;!0===a&&x.submit()}function E(){0<n.filter("div.compact-login").length?(L.hide(),x.hide()):n.hide();I.show();I.find("#UAfpemail").val(n.find("#email").val()).focus();
R||(R=!0,M());f();I.find(".uanotice").hide()}function M(){I.find(".back-to-sign-in").click(function(a){I.hide();n.show();L.show();x.hide();n.find("#signInTypeExisting").attr("checked","checked").click();n.find(".right-side a.back-to-sign-in").click();var b=I.find("#UAfpemail").val();b?(n.find("#email").val(b),n.find("#password").focus()):n.find("#email").focus();I.find("div.uaerr").html("").hide();a.preventDefault()});I.find('input[name="email"]').change(function(){$t=a(this);$t.val($t.val().replace(/^[\s\t\r\n]+|[\s\t\r\n]+$/g,
""))});I.submit(function(){var b=a(this),c=b.find("div.uaerr"),d=b.find("div.uanotice");c.hide();d.hide();var e=b.find("input[name='email']");if(!U(e.val()))return w("invalid_email_address",function(a){b.find("div.uaerr").html(a).fadeIn("fast")}),!1;b.find("input,button").attr("disabled",!0);var f=new UALoaderHover(b);l({data:{page:"forgot-password-send-mail",email:e.val()},complete:function(){b.find("input,button").attr("disabled",!1);f.remove()},success:function(a){200==a.code?(d.html(a.data).fadeIn("fast"),
e.val("")):c.html(a.data).fadeIn("fast")}});return!1})}var n=k.find(".UA-login-signup div.sign-in, div.compact-login"),I=k.find("form.forgot-password"),x=n.find("form.sign-in-new");c=n.find("form.username-form");var L=n.find("form.sign-in-existing"),N=n.find("#skipUsername"),G=n.find("input[name=email]"),S=L.find("input[name=password]"),z=x.find("input[name=email]"),J=x.find("input[name=password]"),B=x.find("input[name=username]"),Q=x.find("input[name=screenname]");(function(){"flipsnack"!=b.terminal&&
n.find("input[type=checkbox],input[type=radio]").each(function(){var b=a(this),c=b.is("[type=checkbox]")?"checkbox":"radio",d=a("<span />").addClass("ST-"+c);b.css("float")&&d.css("float",b.css("float"));d.insertBefore(b).append(b);var e=a("input[name="+b.attr("name")+"]");b.bind("updateState",function(){var c=b.is(":checkbox"),f=b.is(":checked"),g=b.is(":disabled");f?(c||e.each(function(){a(this).parent().removeClass("checked")}),d.addClass("checked")):d.removeClass("checked checkedHover checkedFocus");
g?d.addClass("disabled"):d.removeClass("disabled");c&&(c=d.next(),f?c.val(1):c.val(0))}).trigger("updateState").click(function(){a(this).trigger("updateState")}).focus(function(){d.addClass("focus");"checkbox"==c&&b.is(":checked")&&a(this).addClass("checkedFocus")}).blur(function(){d.removeClass("focus checkedFocus")})})})();(function(){n.find("i.tt").each(function(){a(this).STtooltip({content:n.find("div.toolTipContent"),maxWidth:420})});z.blur(y);Q.blur(A);B.blur(D);J.blur(C)})();var O=n.find('input[name="email"]');
O.change(function(){O.val(a(this).val())});n.find("input[name=signInType]").change(function(){"new"==a(this).val()?(x.show(),L.hide(),"flipsnack"==b.terminal&&(UA_onSignInTypeChange("new"),f(),z.removeClass("err"),J.removeClass("err"))):(x.hide(),L.show(),"flipsnack"==b.terminal&&UA_onSignInTypeChange("existing"));f()});-1!==location.search.indexOf("signup=true")&&n.find("input#signInTypeNew").trigger("click");"signup"===h.page||"create"===h.page||"#register"==document.location.hash||window.goToPageAfterLogin&&
window.goToPageAfterLogin.match(/\bregister=1/)?n.find("#signInTypeNew").click().triggerHandler("updateState"):"forgot-password"===h.page&&E();k.find("a.show-more-link").click(function(a){k.find(".show-more").hide();k.find(".show-more-options").show();a.preventDefault()});k.find(".sign-in-facebook-v2, a.moreFacebook").click(b.showFacebookPopin);k.find(".sign-in-twitter, a.moreTwitter").click(b.showTwitterPopin);k.find("a.moreYahoo").click(function(){b.showOpenIDPopin("yahoo");return!1});k.find(".sign-in-google-new, a.moreGoogle").click(b.showGooglePopin);
x.submit(function(){"flipsnack"==b.terminal?t():v();return!1});L.submit(function(){d();return!1});c.unbind().submit(function(){m();return!1});N.unbind().click(function(){p();return!1});isCanvasSupported()||n.find("input[type=text],input[type=password]").each(function(){a(this).prop("placeholder")&&a(this).before('<label class="no-html5-label">'+a(this).prop("placeholder")+"</label>")});n.find(".right-side a.back-to-sign-in").click(function(){L.show().siblings("form").hide();n.find(".right-side .login").show().siblings("div").hide()});
n.find(".right-side a.create-account").click(function(){x.show().siblings("form").hide();n.find(".right-side .register").show().siblings("div").hide()});n.find("a.forgot-password").click(function(){E();return!1});var R=!1}function U(a){return/^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(a)}function P(a){return"undefined"!=typeof a}function l(c){P(c.data)||(c.data={});c.data.page||(c.data.page=
h.page);c.data.terminal||(c.data.terminal=b.terminal);"undefined"!=typeof b.sessionId&&""!=b.sessionId&&(c.data.PHPSESSID=b.sessionId);"undefined"!=typeof stTrackingSystem&&(c.data.stTrackingSystem=stTrackingSystem);"undefined"!=typeof stTrackingObjectSystem&&(c.data.stTrackingObjectSystem=stTrackingObjectSystem);b.lang&&(c.data.lang=b.lang);a.ajax({url:b.localAjaxUrl,type:b.ajaxType,dataType:b.ajaxDataType,data:c.data,success:function(d){if(d.data.session_expired)b.onSessionExpired();300==d.code?
(b.replaceApiHeader(d.data.header),location.href=b.loginPage):(d.data.points&&a("#UA_points_header").html(d.data.points),"function"==typeof c.success&&c.success(d))},complete:function(){"function"==typeof c.complete&&c.complete()}})}function H(a){if("function"==typeof h.onError)h.onError(a);else"function"==typeof UA_onError?UA_onError(a):alert(a)}function G(c,d){var e=a("<div />").addClass("button").addClass("loaderButton"+d);e.width(c.width()-2);e.height(c.height()-2);var f=a("<img />").attr({src:b.apiUrl+
"images/ajax-loader-"+d+".gif"});e.append(f);c.hide().after(e);return e}function E(){if("klobic"==b.terminal){var c=a(".compact-login");c.find('[data-gatrack="1"]:not([type="text"], [type="password"])').on("click",function(b){b.isTrigger||ga("b.send","event","Login/Register","Click",a(this).attr("data-gatrack-name"))});c.find('[data-gatrack="1"][type="text"], [data-gatrack="1"][type="password"]').on("keydown",function(b){!b.isTrigger&&(""!=a(this).val()&&13==b.keyCode)&&ga("b.send","event","Login/Register",
"Enter",a(this).attr("data-gatrack-name"))})}}function X(c){c.find("a").each(function(){b.analyticsDomainCheck(a(this))});"function"==typeof UA_OnLoadContent&&UA_OnLoadContent(k)}function F(c){var d;d=-1!=a.inArray(h.page,"login signup forgot-password login-signup-compact credit-card-form billing-info-form create".split(" "))?k:k.find("div.userApiContainer");d.html(c.content);d.hide().fadeIn("fast");(!c.logged||"flipsnack"==b.terminal)&&C(c);X(d);E();return d}var k=this,h=a.extend({showLoader:!0},
c);f=k;g=h;h.validS={email:!1,screenname:!1,psw1:!1,psw2:!1};!1==b.inited&&(e(),b.inited=!0);if("flipsnack"==b.terminal&&"account-options"==h.page)c="","en"!=b.lang&&(c="/"+b.lang),location.href=c+"/my-account.html";else{if(0>a.inArray(h.page,"logout check-login set-session auto-login login signup loginx login signup forgot-password get-the-vip add-coupon add-serv buy-points buy-points-bs buy-points-popin credit-card-form billing-info-form".split(" "))){c=a("<img />").attr({src:b.apiUrl+"images/ajax-loader.gif?v2",
"class":"UALoader"});c.css({display:"block",margin:"-16px auto -16px auto",position:"absolute",top:"50%",left:"50%"});k.find("div.userApiContainer").html(c);if(!1==b.isOpen)return b.open(k);0<a(window).scrollTop()&&(a.browser.safari?a("body"):a("html")).animate({scrollTop:0},300)}null!=b.onBuyPointsTimeout&&clearInterval(b.onBuyPointsTimeout);"logout"!=h.page&&a(".userApi.flipsnack .userApiBG, .userApi.photosnack .userApiBG, .userApi.podsnack .userApiBG").css("height","");switch(h.page){default:l({success:function(a){200==
a.code?F(a.data):H(a.data)}});break;case "buy-points-popin":c="#st-buy-points";h.options&&(c+="&options="+h.options);location.href=c;return;case "get-the-vip":b.getTheVip();return;case "buy-points-bs":b._buyPointsBS(h);break;case "buy-points":h.options&&"freeUC"==h.options&&b.freeuserConvert();c={};var v,V,da="service coupon methodBuy views vipOnly type pug upgrade hm flipsnack_api_uploads".split(" ");if(h.plan)switch(h.plan){case "points":c.service="75-points";break;case "vip":c.service="vip-membership-yearly";
break;case "business":c.service="vip-extended-yearly"}h.re&&(c.extraParams||(c.extraParams={}),c.extraParams.re=h.re);for(v=0;V=da[v];v++)h[V]&&(c[V]=h[V]);"klobic"==b.terminal&&(!c.type||"custom-banner-design"!=c.type)?b._buyPointsBS(c):b._buyPoints(c);return;case "point-history":m();break;case "auto-login":t();break;case "login":case "signup":case "forgot-password":D();return;case "login-signup-compact":D("login-signup-compact");return;case "create":D("create-account");return;case "loginx":case "signupx":case "forgot-passwordx":k=
a("#inlineLogin");S();return;case "check-login":u();break;case "account-options":a(".userApi.flipsnack .userApiBG, .userApi.photosnack .userApiBG, .userApi.podsnack .userApiBG").css("height","520px");a(".userApi.klobic .userApiBG").css({height:"auto","min-height":"275px"});ba();break;case "change-password":Z();break;case "change-email":M();break;case "order-history":r();break;case "logout":O();break;case "add-coupon":case "add-serv":case "add-service":d()}var A=0;window.STonProfilePhoto=function(a,
c){var d=k.find("form.UAaccountOptionsForm"),e=k.find("#uploadFileTempForm"+a);d.find("div.browse").append(e.find("input[type=file]"));if(1===parseInt(c)){d.find("div.profilePhotoC .placeholder").hide();d.find("div.profilePhotoC .remove").css("visibility","visible");d.find("div.profilePhotoC img").attr("src",b.filesUrl+"accounts/"+k.find("#UAacchash").val()+"/profile?_="+parseInt(1E4*Math.random()));try{window.UPRefresh()}catch(f){}}else d.find("div.profilePhotoC .remove").css("visibility","hidden"),
d.find(".uanotice").hide(),d.find(".uaerr").html(0==c?"Image not saved":"Only jpeg and png files are accepted").fadeIn("fast"),d.find("div.profilePhotoC img").attr("src")?d.find("div.profilePhotoC .placeholder").show():d.find("div.profilePhotoC img").hide()}}};a.userApi=a.userApi||{};a.userApi=a.extend(b,a.userApi)})(jQuery);
$(document).ready(function(){var a=$.userApi;(a.isLoginPage()||a.isCreateAccountPage())&&$(".UA-hmenu, .UA-signin-b, .UA-likesmenu, #UA-footer, #UA-container .clearfooter, #UA-header.flipsnack .UA-myaccount, #UA-header.flipsnack .menu-icon").hide();var f=$("#UAtext_close").val()||"Close";a.userApiContainerHtml='<div class="userApiBackBG"><div class="userApiHolder"><div class="userApiBG"><div class="userApiContainer"></div></div><a href="#" class="UAclose">'+f+"</a></div></div>";(f=a.getUrlVars())&&
f.uref&&a.cookie("UAuref",f.uref,{expires:365,path:"/"});if(a.sessionExpired)a.onSessionExpired();$("#UA-header").length&&a.initHeader($("#UA-header"));$("a").each(function(){a.analyticsDomainCheck($(this))});window.addEventListener?window.addEventListener("keydown",a.konami,!0):$(document).keydown(a.konami);$(window).hashchange(function(){if("st-buy-points-popin"==location.hash.substring(1).split("&")[0]){if("undefined"===typeof f)var f="upload";pageToLoadPopin=f}a.loadPage();"function"==typeof UA_onHashChange&&
UA_onHashChange()});a.loadPage();setInterval(a.checkSessionStatus,1E3*a.checkSessionStatusTimeout);"flipsnack"!==a.terminal&&(a.isSnackWS()?a.preloadImage("menu-logos-bw.png?v=2.4"):a.preloadImage("menu-logos-bw2.png?v=1"))});var STtooltipIndex=0;
$.fn.STtooltip=function(a){var f={content:"",className:null,width:null};$.extend(f,a);STtooltipIndex++;f.content instanceof jQuery&&(f.content.hide(),f.content=f.content.html());this.attr("ttid","tt"+STtooltipIndex);a=$("<div />").attr("id","tt"+STtooltipIndex).html(f.content).hide();var g=!0;a.hover(function(){$(this).stop(!0,!0).fadeIn("fast");g=!1},function(){$(this).fadeOut("fast")});null!=f.className?a.addClass(f.className):a.addClass("UAtooltip");null!=f.width&&a.css("width",f.width+"px");null!=
f.maxWidth&&a.css("max-width",f.maxWidth+"px");$("body").prepend(a);this.hover(function(){var a=$(this),c=$("#"+a.attr("ttid")),e=$(window),d=a.offset(),f=d.top+a.height()+2;e.height()+e.scrollTop()-c.innerHeight()<f&&(f-=c.innerHeight()+a.height()+4,f<e.scrollTop()&&(f=e.scrollTop()));a=d.left+a.width()/2;d=c.outerWidth();e=e.width()-d;a>e&&(a=e);c.css({left:a+"px",top:f+"px"});c.stop(!0,!0).fadeIn("fast")},function(){var a=$("#"+$(this).attr("ttid"));setTimeout(function(){!0==g&&a.fadeOut("fast");
g=!0},200)})};$.fn.tooltip||($.fn.tooltip=$.fn.STtooltip);
var UAClipboard={version:"1.0.7",clients:{},moviePath:$.userApi.apiUrl+"js/UAClipboard.swf",nextId:1,$:function(a){"string"==typeof a&&(a=document.getElementById(a));if(!a)return!1;a.addClass||(a.hide=function(){this.style.display="none"},a.show=function(){this.style.display=""},a.addClass=function(a){this.removeClass(a);this.className+=" "+a},a.removeClass=function(a){for(var g=this.className.split(/\s+/),b=-1,c=0;c<g.length;c++)g[c]==a&&(b=c,c=g.length);-1<b&&(g.splice(b,1),this.className=g.join(" "));
return this},a.hasClass=function(a){return!!this.className.match(RegExp("\\s*"+a+"\\s*"))});return a},setMoviePath:function(a){this.moviePath=a},dispatch:function(a,f,g){(a=this.clients[a])&&a.receiveEvent(f,g)},register:function(a,f){this.clients[a]=f},getDOMObjectPosition:function(a,f){for(var g={left:0,top:0,width:a.width?a.width:a.offsetWidth,height:a.height?a.height:a.offsetHeight};a&&a!=f;)g.left+=a.offsetLeft,g.top+=a.offsetTop,a=a.offsetParent;return g},Client:function(a){this.handlers={};
this.id=UAClipboard.nextId++;this.movieId="ZeroClipboardMovie_"+this.id;UAClipboard.register(this.id,this);a&&this.glue(a)}};
UAClipboard.Client.prototype={id:0,ready:!1,movie:null,clipText:"",handCursorEnabled:!0,cssEffects:!0,handlers:null,glue:function(a,f,g){if(this.domElement=UAClipboard.$(a)){"string"==typeof f?f=UAClipboard.$(f):"undefined"==typeof f&&(f=document.getElementsByTagName("body")[0]);a=UAClipboard.getDOMObjectPosition(this.domElement,f);this.div=document.createElement("div");f=this.div.style;f.position="absolute";f.left="0px";f.top="0px";f.width=""+a.width+"px";f.height=""+a.height+"px";if("object"==typeof g)for(addedStyle in g)f[addedStyle]=
g[addedStyle];this.domElement.appendChild(this.div);this.div.innerHTML=this.getHTML(a.width,a.height)}},getHTML:function(a,f){var g="",b="id="+this.id+"&width="+a+"&height="+f;if(navigator.userAgent.match(/MSIE/))var c=location.href.match(/^https/i)?"https://":"http://",g=g+('<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="'+c+'download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0" width="'+a+'" height="'+f+'" id="'+this.movieId+'" align="middle"><param name="allowScriptAccess" value="always" /><param name="allowFullScreen" value="false" /><param name="movie" value="'+
UAClipboard.moviePath+'" /><param name="loop" value="false" /><param name="menu" value="false" /><param name="quality" value="best" /><param name="bgcolor" value="#ffffff" /><param name="flashvars" value="'+b+'"/><param name="wmode" value="transparent"/></object>');else g+='<embed id="'+this.movieId+'" src="'+UAClipboard.moviePath+'" loop="false" menu="false" quality="best" bgcolor="#ffffff" width="'+a+'" height="'+f+'" name="'+this.movieId+'" align="middle" allowScriptAccess="always" allowFullScreen="false" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" flashvars="'+
b+'" wmode="transparent" />';return g},hide:function(){this.div&&(this.div.style.left="-2000px")},show:function(){this.reposition()},destroy:function(){if(this.domElement&&this.div){this.hide();this.div.innerHTML="";var a=document.getElementsByTagName("body")[0];try{a.removeChild(this.div)}catch(f){}this.div=this.domElement=null}},reposition:function(a){a&&((this.domElement=UAClipboard.$(a))||this.hide());if(this.domElement&&this.div){a=UAClipboard.getDOMObjectPosition(this.domElement);var f=this.div.style;
f.left=""+a.left+"px";f.top=""+a.top+"px"}},setText:function(a){this.clipText=a;this.ready&&this.movie.setText(a)},addEventListener:function(a,f){a=a.toString().toLowerCase().replace(/^on/,"");this.handlers[a]||(this.handlers[a]=[]);this.handlers[a].push(f)},setHandCursor:function(a){this.handCursorEnabled=a;this.ready&&this.movie.setHandCursor(a)},setCSSEffects:function(a){this.cssEffects=!!a},receiveEvent:function(a,f){a=a.toString().toLowerCase().replace(/^on/,"");switch(a){case "load":this.movie=
document.getElementById(this.movieId);if(!this.movie){var g=this;setTimeout(function(){g.receiveEvent("load",null)},1);return}if(!this.ready&&navigator.userAgent.match(/Firefox/)&&navigator.userAgent.match(/Windows/)){g=this;setTimeout(function(){g.receiveEvent("load",null)},100);this.ready=!0;return}this.ready=!0;this.movie.setText(this.clipText);this.movie.setHandCursor(this.handCursorEnabled);break;case "mouseover":this.domElement&&this.cssEffects&&(this.domElement.addClass("hover"),this.recoverActive&&
this.domElement.addClass("active"));break;case "mouseout":this.domElement&&this.cssEffects&&(this.recoverActive=!1,this.domElement.hasClass("active")&&(this.domElement.removeClass("active"),this.recoverActive=!0),this.domElement.removeClass("hover"));break;case "mousedown":this.domElement&&this.cssEffects&&this.domElement.addClass("active");break;case "mouseup":this.domElement&&this.cssEffects&&(this.domElement.removeClass("active"),this.recoverActive=!1)}if(this.handlers[a])for(var b=0,c=this.handlers[a].length;b<
c;b++){var e=this.handlers[a][b];if("function"==typeof e)e(this,f);else if("object"==typeof e&&2==e.length)e[0][e[1]](this,f);else if("string"==typeof e)window[e](this,f)}}};
var UALoaderHover=function(a){this.hoverElement=a;var f=$('<div class="UA-loader-hover"><div class="UA-loader-overlay"></div></div>');f.append(this.getHtml5Loader());var g=a.offset(),b=a.outerWidth(),c=a.outerHeight();f.css({left:g.left+"px",top:g.top+"px",height:c,width:b});this.originalOpacity=1;a.fadeTo(100,0.4);$("body").append(f);this.loader=f;var e=this;this.offsetInterval=setInterval(function(){if(!a.closest("html").length)return e.remove(),!1;var d=a.offset(),t=a.outerWidth(),q=a.outerHeight();
if(d.top!==g.top||d.left!==g.left||q!==c||t!==b)f.css({left:d.left+"px",top:d.top+"px",height:q,width:t}),g=d,b=t,c=q},100)};
UALoaderHover.prototype={setSmallSize:function(a){a?this.loader.addClass("small"):this.loader.removeClass("small")},setMediumSize:function(a){a?this.loader.addClass("medium"):this.loader.removeClass("medium")},setTransparent:function(a){a?this.loader.addClass("transparent"):this.loader.removeClass("transparent")},setZIndex:function(a){this.loader.css("z-index",a)},setOriginalOpacity:function(a){this.originalOpacity=a},remove:function(){clearInterval(this.offsetInterval);this.hoverElement.stop().fadeTo(100,
this.originalOpacity);this.loader.remove()},getHtml5Loader:function(){return $('<div class="UA-loader-html5"><div class="f_circleG frotateG_01"></div><div class="f_circleG frotateG_02"></div><div class="f_circleG frotateG_03"></div><div class="f_circleG frotateG_04"></div><div class="f_circleG frotateG_05"></div><div class="f_circleG frotateG_06"></div><div class="f_circleG frotateG_07"></div><div class="f_circleG frotateG_08"></div></div>')}};"undefined"==typeof window.console&&(window.console={log:function(a){}});
